- hosts: dev

  tasks:
    - name: download tomcat from dlcdn
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz"
        dest: "/root/"

    - name: untar the apache file
      command: tar -zxvf apache-tomcat-9.0.80.tar.gz
        #unarchive:
        #src: "apache-tomcat-9.0.80.tar.gz"
        #dest: "/root/"

    - name: rename the tomcat
      command: mv apache-tomcat-9.0.80 tomcat
      tags: abc

    - name: install java
      command: yum install java-1.8.0-openjdk -y

      
how find file: find / -name context.xml (context.xml :file name)

    - name: setting the roles in tomcat-user.xml file
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml
<role rolename="manager-gui"/>
  <role rolename="manager-script"/>
  <user username="tomcat" password="raham123" roles="manager-gui, manager-script"/>


    - name: delete two lines No 21 & 22 in context.xml
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml
        
[21 <Valve className="org.apache.catalina.valves.RemoteAddrValve"
 22          allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> ]
 
    - name: start the tomcat
      shell: nohup /root/tomcat/bin/startup.sh
    command: ./bin/startup.sh

Step-7: Install Deploy to Container
Step-8: go to jenkins>>add post build step>>deploy war ear to container 
step-9: ADD CONTAINER -9
STEP-10: POST BUILD ACTION --> DEPLOY TO EAR/WAR CONTAINER --> DETAILS 
[target/*.war & /swiggy application]
GIVE TOMCAT URL AND TOMCAT CREDENTIALS_(USERNAME:TOMCAT, PASSWORD:tomcat)

ticketing tool ;- Sharepoint 
